# -*- coding: utf-8 -*-
"""11ML_med_final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOOrVIoUtd-UgbQallzwrtFs0yicY6fh

# 0. Setup
"""

import kagglehub
data_path = kagglehub.dataset_download('danielagluj/sleep-30s-spectrograms-from-dodh-dataset')

import shutil
import os

src = data_path
dst = "/content/data"
if not os.path.exists(dst):
    shutil.copytree(src, dst)

!pip install -q segmentation-models-pytorch albumentations opencv-python scikit-image

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import torchvision.models as models
from sklearn.metrics import classification_report, confusion_matrix, cohen_kappa_score
from tqdm import tqdm
import time
import random
seed = 11
random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

"""# 1. EDA"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from collections import Counter
import cv2
from PIL import Image
import warnings
warnings.filterwarnings('ignore')

plt.style.use('default')
sns.set_palette("husl")

TRAIN_PATH = '/content/data/sleep_spectrogram_dataset'
TEST_PATH = '/content/data/test_set_unseen_sub015'

CLASSES = ['W', 'N1', 'N2', 'N3', 'REM']

TRAIN_PATH, TEST_PATH, CLASSES

def get_dataset_stats(data_path, classes):
    stats = {
        'class': [],
        'num_images': [],
        'patient_ids': []
    }

    for cls in classes:
        class_path = os.path.join(data_path, cls)
        if not os.path.exists(class_path):
            print(f"Warning: {class_path} does not exist")
            continue

        files = [f for f in os.listdir(class_path) if f.endswith('.png')]

        patient_ids = set()
        for f in files:
            patient_id = f.split('_')[0]
            patient_ids.add(patient_id)

        stats['class'].append(cls)
        stats['num_images'].append(len(files))
        stats['patient_ids'].append(patient_ids)

    df = pd.DataFrame({
        'class': stats['class'],
        'num_images': stats['num_images'],
        'num_patients': [len(pids) for pids in stats['patient_ids']]
    })

    return df, stats['patient_ids']

train_stats, train_patient_ids = get_dataset_stats(TRAIN_PATH, CLASSES)
print(train_stats)
print(f"\nTotal training images: {train_stats['num_images'].sum()}")
print(f"Total unique patients in train: {len(set.union(*train_patient_ids))}")

test_stats, test_patient_ids = get_dataset_stats(TEST_PATH, CLASSES)
print(test_stats)
print(f"\nTotal test images: {test_stats['num_images'].sum()}")
print(f"Total unique patients in test: {len(set.union(*test_patient_ids))}")

train_patients = set.union(*train_patient_ids)
test_patients = set.union(*test_patient_ids)
overlap = train_patients.intersection(test_patients)
print(f"\nPatient overlap between train and test: {overlap}")
if len(overlap) == 0:
    print("No patient leakage detected")
else:
    print("Patient leakage")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].bar(train_stats['class'], train_stats['num_images'], color='steelblue', alpha=0.7)
axes[0].set_title('Training Set: Class Distribution', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Sleep Stage')
axes[0].set_ylabel('Number of Images')
axes[0].grid(axis='y', alpha=0.3)
for i, v in enumerate(train_stats['num_images']):
    axes[0].text(i, v + 50, str(v), ha='center', va='bottom', fontweight='bold')

axes[1].bar(test_stats['class'], test_stats['num_images'], color='coral', alpha=0.7)
axes[1].set_title('Test Set: Class Distribution', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Sleep Stage')
axes[1].set_ylabel('Number of Images')
axes[1].grid(axis='y', alpha=0.3)
for i, v in enumerate(test_stats['num_images']):
    axes[1].text(i, v + 5, str(v), ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.show()

imbalance_ratio = train_stats['num_images'].max() / train_stats['num_images'].min()
print(f"\nClass imbalance ratio (max/min): {imbalance_ratio:.2f}")
if imbalance_ratio > 3:
    print("Significant class imbalance detected - consider using class weights or resampling")

def get_patient_epoch_distribution(data_path, classes):
    patient_epoch_count = {}

    for cls in classes:
        class_path = os.path.join(data_path, cls)
        if not os.path.exists(class_path):
            continue

        files = [f for f in os.listdir(class_path) if f.endswith('.png')]

        for f in files:
            patient_id = f.split('_')[0]
            if patient_id not in patient_epoch_count:
                patient_epoch_count[patient_id] = 0
            patient_epoch_count[patient_id] += 1

    return patient_epoch_count

train_patient_dist = get_patient_epoch_distribution(TRAIN_PATH, CLASSES)
test_patient_dist = get_patient_epoch_distribution(TEST_PATH, CLASSES)

print("PATIENT EPOCH DISTRIBUTION (TRAIN)")
for patient, count in sorted(train_patient_dist.items()):
    print(f"{patient}: {count} epochs")

print(f"\nAverage epochs per patient (train): {np.mean(list(train_patient_dist.values())):.1f}")
print(f"Min epochs per patient (train): {np.min(list(train_patient_dist.values()))}")
print(f"Max epochs per patient (train): {np.max(list(train_patient_dist.values()))}")

print("\nPATIENT EPOCH DISTRIBUTION (TEST)")
for patient, count in sorted(test_patient_dist.items()):
    print(f"{patient}: {count} epochs")

def visualize_samples(data_path, classes, num_samples=3):
    fig, axes = plt.subplots(len(classes), num_samples, figsize=(15, 12))

    for i, cls in enumerate(classes):
        class_path = os.path.join(data_path, cls)
        if not os.path.exists(class_path):
            continue

        files = [f for f in os.listdir(class_path) if f.endswith('.png')]
        selected_files = np.random.choice(files, min(num_samples, len(files)), replace=False)

        for j, file in enumerate(selected_files):
            img_path = os.path.join(class_path, file)
            img = Image.open(img_path)

            axes[i, j].imshow(img)
            axes[i, j].axis('off')

            if j == 0:
                axes[i, j].set_title(f'{cls}\n{file}', fontsize=10, fontweight='bold', loc='left')
            else:
                axes[i, j].set_title(file, fontsize=9)

    plt.suptitle('Sample Spectrograms per Sleep Stage', fontsize=16, fontweight='bold', y=0.995)
    plt.tight_layout()
    plt.show()

visualize_samples(TRAIN_PATH, CLASSES, num_samples=3)

def analyze_image_properties(data_path, classes, num_samples=10):
    properties = {
        'shapes': [],
        'dtypes': [],
        'mean_values': [],
        'std_values': []
    }

    for cls in classes:
        class_path = os.path.join(data_path, cls)
        if not os.path.exists(class_path):
            continue

        files = [f for f in os.listdir(class_path) if f.endswith('.png')]
        selected_files = np.random.choice(files, min(num_samples, len(files)), replace=False)

        for file in selected_files:
            img_path = os.path.join(class_path, file)
            img = np.array(Image.open(img_path))

            properties['shapes'].append(img.shape)
            properties['dtypes'].append(img.dtype)
            properties['mean_values'].append(img.mean())
            properties['std_values'].append(img.std())

    return properties

props = analyze_image_properties(TRAIN_PATH, CLASSES, num_samples=10)

print(f"Unique shapes: {set(props['shapes'])}")
print(f"Unique dtypes: {set(props['dtypes'])}")
print(f"Mean pixel value (avg): {np.mean(props['mean_values']):.2f}")
print(f"Std pixel value (avg): {np.mean(props['std_values']):.2f}")
print(f"Min mean across images: {np.min(props['mean_values']):.2f}")
print(f"Max mean across images: {np.max(props['mean_values']):.2f}")

def compute_mean_spectrogram(data_path, classes, num_samples=50):
    mean_spectrograms = {}

    for cls in classes:
        class_path = os.path.join(data_path, cls)
        if not os.path.exists(class_path):
            continue

        files = [f for f in os.listdir(class_path) if f.endswith('.png')]
        selected_files = np.random.choice(files, min(num_samples, len(files)), replace=False)

        images = []
        for file in selected_files:
            img_path = os.path.join(class_path, file)
            img = np.array(Image.open(img_path)).astype(np.float32)
            images.append(img)

        mean_spectrograms[cls] = np.mean(images, axis=0)

    return mean_spectrograms

mean_specs = compute_mean_spectrogram(TRAIN_PATH, CLASSES, num_samples=50)

fig, axes = plt.subplots(1, len(CLASSES), figsize=(18, 4))

for i, cls in enumerate(CLASSES):
    if cls in mean_specs:
        axes[i].imshow(mean_specs[cls].astype(np.uint8))
        axes[i].set_title(f'{cls}\nMean Spectrogram', fontweight='bold')
        axes[i].axis('off')

plt.suptitle('Average Spectrograms per Sleep Stage', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print(f"   Total training images: {train_stats['num_images'].sum()}")
print(f"   Total test images: {test_stats['num_images'].sum()}")
print(f"   Number of classes: {len(CLASSES)}")
print(f"   Classes: {CLASSES}")

print(f"   Unique patients in train: {len(set.union(*train_patient_ids))}")
print(f"   Unique patients in test: {len(set.union(*test_patient_ids))}")
print(f"   Patient leakage: {'No' if len(train_patients.intersection(test_patients)) == 0 else 'Yes'}")

print(train_stats[['class', 'num_images']].to_string(index=False))
imb_ratio = train_stats['num_images'].max() / train_stats['num_images'].min()
print(f"   Imbalance ratio: {imb_ratio:.2f}")

print(f"   Shape: {list(set(props['shapes']))[0]}")
print(f"   Dtype: {list(set(props['dtypes']))[0]}")
print(f"   Pixel value range: ~0-255")

if imb_ratio > 3:
    print("- Use class weights due to imbalance")
else:
    print("- Class balance is acceptable")

"""# Dataset handling"""

class SleepSpectrogramDataset(Dataset):
    def __init__(self, data_path, classes, transform=None):
        self.data_path = data_path
        self.classes = classes
        self.transform = transform
        self.class_to_idx = {cls: idx for idx, cls in enumerate(classes)}

        self.samples = []
        for cls in classes:
            class_path = os.path.join(data_path, cls)
            if not os.path.exists(class_path):
                continue

            files = [f for f in os.listdir(class_path) if f.endswith('.png')]
            for f in files:
                self.samples.append((os.path.join(class_path, f), self.class_to_idx[cls]))

        print(f"Loaded {len(self.samples)} samples from {data_path}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]

        img = Image.open(img_path)

        if img.mode == 'RGBA':
            img = img.convert('RGB')

        if self.transform:
            img = self.transform(img)

        return img, label

"""# Augmentation (ImageNet not flip)"""

class SpecAugment:
    def __init__(self, freq_mask_param=8, time_mask_param=5, num_freq_masks=2, num_time_masks=2, p=0.5):
        self.freq_mask_param = freq_mask_param
        self.time_mask_param = time_mask_param
        self.num_freq_masks = num_freq_masks
        self.num_time_masks = num_time_masks
        self.p = p

    def __call__(self, img):
        import torch

        if torch.rand(1).item() > self.p:
            return img

        C, H, W = img.shape
        img = img.clone()

        for _ in range(self.num_freq_masks):
            f = torch.randint(1, self.freq_mask_param + 1, (1,)).item()
            f0 = torch.randint(0, max(1, H - f + 1), (1,)).item()
            img[:, f0:f0+f, :] = 0

        for _ in range(self.num_time_masks):
            t = torch.randint(1, self.time_mask_param + 1, (1,)).item()
            t0 = torch.randint(0, max(1, W - t + 1), (1,)).item()
            img[:, :, t0:t0+t] = 0

        return img

spec_augment = SpecAugment(freq_mask_param=8, time_mask_param=5, num_freq_masks=2, num_time_masks=2, p=0.5)
print("Parameters: freq_mask=8Hz, time_mask=5 steps, 2 masks each, p=0.5")

train_transform = transforms.Compose([
    transforms.RandomRotation(degrees=5),
    transforms.RandomAffine(degrees=0, translate=(0.05, 0.05)),
    transforms.ColorJitter(brightness=0.1, contrast=0.1),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    SpecAugment(freq_mask_param=8, time_mask_param=5, num_freq_masks=2, num_time_masks=2, p=0.5)
])

test_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

"""# Data loader"""

train_dataset = SleepSpectrogramDataset(TRAIN_PATH, CLASSES, transform=train_transform)
test_dataset = SleepSpectrogramDataset(TEST_PATH, CLASSES, transform=test_transform)

BATCH_SIZE = 32

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

print(f"Train batches: {len(train_loader)}")
print(f"Test batches: {len(test_loader)}")

class_counts = train_stats['num_images'].values
total_samples = sum(class_counts)
class_weights = torch.FloatTensor([total_samples / (len(class_counts) * count) for count in class_counts])
class_weights = class_weights.to(device)

print(f"\nClass weights (to handle imbalance):")
for i, cls in enumerate(CLASSES):
    print(f"  {cls}: {class_weights[i]:.3f}")

"""# Model

## Custom CNN
"""

class CustomCNN(nn.Module):
    def __init__(self, num_classes=5):
        super(CustomCNN, self).__init__()

        self.features = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(256, 512, kernel_size=3, padding=1),
            nn.BatchNorm2d(512),
            nn.ReLU(inplace=True),
            nn.AdaptiveAvgPool2d((1, 1))
        )

        self.classifier = nn.Sequential(
            nn.Dropout(0.5),
            nn.Linear(512, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        x = self.classifier(x)
        return x

model_custom = CustomCNN(num_classes=len(CLASSES))
total_params = sum(p.numel() for p in model_custom.parameters())
trainable_params = sum(p.numel() for p in model_custom.parameters() if p.requires_grad)

print(f"Custom CNN Architecture:")
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Model size: ~{total_params * 4 / (1024**2):.2f} MB")

"""## Pretrained models"""

def create_resnet18(num_classes=5, pretrained=True):
    model = models.resnet18(pretrained=pretrained)
    num_ftrs = model.fc.in_features
    model.fc = nn.Linear(num_ftrs, num_classes)
    return model

def create_efficientnet_b0(num_classes=5, pretrained=True):
    model = models.efficientnet_b0(pretrained=pretrained)
    num_ftrs = model.classifier[1].in_features
    model.classifier[1] = nn.Linear(num_ftrs, num_classes)
    return model

def create_mobilenet_v2(num_classes=5, pretrained=True):
    model = models.mobilenet_v2(pretrained=pretrained)
    num_ftrs = model.classifier[1].in_features
    model.classifier[1] = nn.Linear(num_ftrs, num_classes)
    return model

model_resnet = create_resnet18(num_classes=len(CLASSES), pretrained=True)
model_efficientnet = create_efficientnet_b0(num_classes=len(CLASSES), pretrained=True)
model_mobilenet = create_mobilenet_v2(num_classes=len(CLASSES), pretrained=True)

for name, model in [("ResNet18", model_resnet), ("EfficientNet-B0", model_efficientnet), ("MobileNetV2", model_mobilenet)]:
    total = sum(p.numel() for p in model.parameters())
    print(f"{name}: {total:,} parameters")

"""# Train + val"""

def train_epoch(model, train_loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    pbar = tqdm(train_loader, desc='Training')
    for inputs, labels in pbar:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        pbar.set_postfix({'loss': running_loss/len(pbar), 'acc': 100.*correct/total})

    epoch_loss = running_loss / len(train_loader)
    epoch_acc = 100. * correct / total

    return epoch_loss, epoch_acc

def validate(model, test_loader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        pbar = tqdm(test_loader, desc='Validation')
        for inputs, labels in pbar:
            inputs, labels = inputs.to(device), labels.to(device)

            outputs = model(inputs)
            loss = criterion(outputs, labels)

            running_loss += loss.item()
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

            pbar.set_postfix({'loss': running_loss/len(pbar), 'acc': 100.*correct/total})

    epoch_loss = running_loss / len(test_loader)
    epoch_acc = 100. * correct / total

    return epoch_loss, epoch_acc, all_preds, all_labels

print("Training and validation functions defined")

class EarlyStopping:
    def __init__(self, patience=7, min_delta=0, verbose=True):
        self.patience = patience
        self.min_delta = min_delta
        self.verbose = verbose
        self.counter = 0
        self.best_loss = None
        self.early_stop = False
        self.val_loss_min = float('inf')

    def __call__(self, val_loss):
        if self.best_loss is None:
            self.best_loss = val_loss
        elif val_loss > self.best_loss - self.min_delta:
            self.counter += 1
            if self.verbose:
                print(f'EarlyStopping counter: {self.counter} out of {self.patience}')
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_loss = val_loss
            self.counter = 0

def train_model_with_early_stopping(model, model_name, train_loader, test_loader, criterion, optimizer, scheduler, num_epochs, device, patience=7):

    early_stopping = EarlyStopping(patience=patience, min_delta=0.001, verbose=True)

    best_acc = 0.0
    best_epoch = 0
    train_history = {'loss': [], 'acc': []}
    val_history = {'loss': [], 'acc': []}

    print(f"\nTraining {model_name}")
    print("="*60)

    for epoch in range(num_epochs):
        print(f"\nEpoch {epoch+1}/{num_epochs}")

        train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc, val_preds, val_labels = validate(model, test_loader, criterion, device)

        train_history['loss'].append(train_loss)
        train_history['acc'].append(train_acc)
        val_history['loss'].append(val_loss)
        val_history['acc'].append(val_acc)

        if scheduler:
            scheduler.step()

        print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}%")
        print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")

        if val_acc > best_acc:
            best_acc = val_acc
            best_epoch = epoch + 1
            torch.save(model.state_dict(), f'/content/{model_name}_best.pth')
            print(f"Best model saved! Val Acc: {best_acc:.2f}%")

        early_stopping(val_loss)
        if early_stopping.early_stop:
            print(f"\nEarly stopping triggered at epoch {epoch+1}")
            break

    print("\n" + "="*60)
    print(f"Training completed for {model_name}")
    print(f"Best Val Acc: {best_acc:.2f}% at epoch {best_epoch}")
    if early_stopping.early_stop:
        print(f"Stopped early after {epoch+1} epochs (patience={patience})")

    return train_history, val_history, best_acc

print("Training loop with early stopping defined")

def train_model_differential_lr(model, model_name, train_loader, test_loader, criterion,
                                backbone_lr, head_lr, num_epochs, device,
                                freeze_epochs=3, patience=10, is_pretrained=True):

    if is_pretrained:
        if hasattr(model, 'fc'):
            backbone_params = [p for n, p in model.named_parameters() if 'fc' not in n]
            head_params = [p for n, p in model.named_parameters() if 'fc' in n]
        elif hasattr(model, 'classifier'):
            backbone_params = [p for n, p in model.named_parameters() if 'classifier' not in n]
            head_params = [p for n, p in model.named_parameters() if 'classifier' in n]
        else:
            backbone_params = []
            head_params = list(model.parameters())

        for param in backbone_params:
            param.requires_grad = False

        optimizer = optim.Adam([
            {'params': head_params, 'lr': head_lr}
        ])

        print(f"Phase 1: Freezing backbone, training head with LR={head_lr}")
    else:
        optimizer = optim.Adam(model.parameters(), lr=head_lr)
        print(f"Training from scratch with LR={head_lr}")

    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=3)
    early_stopping = EarlyStopping(patience=patience, min_delta=0.001, verbose=True)

    best_acc = 0.0
    best_epoch = 0
    train_history = {'loss': [], 'acc': []}
    val_history = {'loss': [], 'acc': []}
    phase = 1

    print(f"\nTraining {model_name}")
    print("="*60)

    for epoch in range(num_epochs):
        if is_pretrained and epoch == freeze_epochs and phase == 1:
            print(f"\nPhase 2: Unfreezing backbone")
            for param in backbone_params:
                param.requires_grad = True

            optimizer = optim.Adam([
                {'params': backbone_params, 'lr': backbone_lr},
                {'params': head_params, 'lr': head_lr}
            ])
            scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=3)
            print(f"Backbone LR={backbone_lr}, Head LR={head_lr}")
            phase = 2

        print(f"\nEpoch {epoch+1}/{num_epochs}")

        train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc, val_preds, val_labels = validate(model, test_loader, criterion, device)

        train_history['loss'].append(train_loss)
        train_history['acc'].append(train_acc)
        val_history['loss'].append(val_loss)
        val_history['acc'].append(val_acc)

        scheduler.step(val_loss)

        print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}%")
        print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")

        if val_acc > best_acc:
            best_acc = val_acc
            best_epoch = epoch + 1
            torch.save(model.state_dict(), f'/content/{model_name}_best.pth')
            print(f"Best model saved! Val Acc: {best_acc:.2f}%")

        early_stopping(val_loss)
        if early_stopping.early_stop:
            print(f"\nEarly stopping triggered at epoch {epoch+1}")
            break

    print("\n" + "="*60)
    print(f"Training completed for {model_name}")
    print(f"Best Val Acc: {best_acc:.2f}% at epoch {best_epoch}")
    if early_stopping.early_stop:
        print(f"Stopped early after {epoch+1} epochs (patience={patience})")

    return train_history, val_history, best_acc

print("Training function with differential LR and ReduceLROnPlateau defined")

"""# Eval"""

def evaluate_model(model, test_loader, device, model_name):
    model.eval()
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for inputs, labels in tqdm(test_loader, desc='Evaluating'):
            inputs = inputs.to(device)
            outputs = model(inputs)
            _, predicted = outputs.max(1)

            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.numpy())

    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    print(f"\n{'='*60}")
    print(f"Evaluation Results: {model_name}")
    print(f"{'='*60}\n")

    print("Classification Report:")
    print(classification_report(all_labels, all_preds, target_names=CLASSES, digits=4))

    cm = confusion_matrix(all_labels, all_preds)
    print("\nConfusion Matrix:")
    print(cm)

    kappa = cohen_kappa_score(all_labels, all_preds)
    print(f"\nCohen's Kappa Score: {kappa:.4f}")

    accuracy = (all_preds == all_labels).mean() * 100
    print(f"Overall Accuracy: {accuracy:.2f}%")

    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASSES, yticklabels=CLASSES)
    plt.title(f'Confusion Matrix - {model_name}')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    plt.savefig(f'/content/{model_name}_confusion_matrix.png', dpi=150)
    plt.show()

    return {
        'predictions': all_preds,
        'labels': all_labels,
        'accuracy': accuracy,
        'kappa': kappa,
        'confusion_matrix': cm
    }

print("Evaluation function defined")

"""# Start

### Custom
"""

NUM_EPOCHS = 3000
LEARNING_RATE = 0.001
PATIENCE = 7

model_custom = CustomCNN(num_classes=len(CLASSES)).to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights)

train_hist_custom, val_hist_custom, best_acc_custom = train_model_differential_lr(
    model=model_custom,
    model_name="CustomCNN",
    train_loader=train_loader,
    test_loader=test_loader,
    criterion=criterion,
    backbone_lr=0.001,
    head_lr=0.001,
    num_epochs=NUM_EPOCHS,
    device=device,
    freeze_epochs=0,
    patience=PATIENCE,
    is_pretrained=False
)

"""### Resnet18"""

NUM_EPOCHS = 3000
BACKBONE_LR = 0.00001
HEAD_LR = 0.001
FREEZE_EPOCHS = 3
PATIENCE = 10

model_resnet = create_resnet18(num_classes=len(CLASSES), pretrained=True).to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights)

train_hist_resnet, val_hist_resnet, best_acc_resnet = train_model_differential_lr(
    model=model_resnet,
    model_name="ResNet18_v2",
    train_loader=train_loader,
    test_loader=test_loader,
    criterion=criterion,
    backbone_lr=BACKBONE_LR,
    head_lr=HEAD_LR,
    num_epochs=NUM_EPOCHS,
    device=device,
    freeze_epochs=FREEZE_EPOCHS,
    patience=PATIENCE,
    is_pretrained=True
)

"""### EfficientNet-B0"""

NUM_EPOCHS = 3000
BACKBONE_LR = 0.00001
HEAD_LR = 0.001
FREEZE_EPOCHS = 3
PATIENCE = 10

model_efficientnet = create_efficientnet_b0(num_classes=len(CLASSES), pretrained=True).to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights)

train_hist_effnet, val_hist_effnet, best_acc_effnet = train_model_differential_lr(
    model=model_efficientnet,
    model_name="EfficientNet-B0_v2",
    train_loader=train_loader,
    test_loader=test_loader,
    criterion=criterion,
    backbone_lr=BACKBONE_LR,
    head_lr=HEAD_LR,
    num_epochs=NUM_EPOCHS,
    device=device,
    freeze_epochs=FREEZE_EPOCHS,
    patience=PATIENCE,
    is_pretrained=True
)

"""### MobileNet"""

NUM_EPOCHS = 3000
BACKBONE_LR = 0.00001
HEAD_LR = 0.001
FREEZE_EPOCHS = 3
PATIENCE = 10

model_mobilenet = create_mobilenet_v2(num_classes=len(CLASSES), pretrained=True).to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights)

train_hist_mobile, val_hist_mobile, best_acc_mobile = train_model_differential_lr(
    model=model_mobilenet,
    model_name="MobileNetV2_v2",
    train_loader=train_loader,
    test_loader=test_loader,
    criterion=criterion,
    backbone_lr=BACKBONE_LR,
    head_lr=HEAD_LR,
    num_epochs=NUM_EPOCHS,
    device=device,
    freeze_epochs=FREEZE_EPOCHS,
    patience=PATIENCE,
    is_pretrained=True
)

"""## Evaluate"""

model_custom.load_state_dict(torch.load('/content/CustomCNN_best.pth'))
results_custom = evaluate_model(model_custom, test_loader, device, "CustomCNN")

model_resnet.load_state_dict(torch.load('/content/ResNet18_v2_best.pth'))
results_resnet = evaluate_model(model_resnet, test_loader, device, "ResNet18")

model_efficientnet.load_state_dict(torch.load('/content/EfficientNet-B0_v2_best.pth'))
results_effnet = evaluate_model(model_efficientnet, test_loader, device, "EfficientNet-B0")

model_mobilenet.load_state_dict(torch.load('/content/MobileNetV2_v2_best.pth'))
results_mobile = evaluate_model(model_mobilenet, test_loader, device, "MobileNetV2")

comparison_df = pd.DataFrame({
    'Model': ['CustomCNN', 'ResNet18', 'EfficientNet-B0', 'MobileNetV2'],
    'Best Val Acc': [best_acc_custom, best_acc_resnet, best_acc_effnet, best_acc_mobile],
    'Test Acc': [results_custom['accuracy'], results_resnet['accuracy'],
                 results_effnet['accuracy'], results_mobile['accuracy']],
    'Cohen Kappa': [results_custom['kappa'], results_resnet['kappa'],
                    results_effnet['kappa'], results_mobile['kappa']]
})

print("\n" + "="*70)
print("MODEL COMPARISON")
print("="*70)
print(comparison_df.to_string(index=False))
print("="*70)

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

x_pos = np.arange(len(comparison_df))
axes[0].bar(x_pos, comparison_df['Test Acc'], color=['steelblue', 'coral', 'green', 'purple'], alpha=0.7)
axes[0].set_xticks(x_pos)
axes[0].set_xticklabels(comparison_df['Model'], rotation=45, ha='right')
axes[0].set_ylabel('Accuracy (%)')
axes[0].set_title('Test Accuracy Comparison', fontweight='bold')
axes[0].grid(axis='y', alpha=0.3)
for i, v in enumerate(comparison_df['Test Acc']):
    axes[0].text(i, v + 0.5, f"{v:.2f}%", ha='center', va='bottom', fontweight='bold')

axes[1].bar(x_pos, comparison_df['Cohen Kappa'], color=['steelblue', 'coral', 'green', 'purple'], alpha=0.7)
axes[1].set_xticks(x_pos)
axes[1].set_xticklabels(comparison_df['Model'], rotation=45, ha='right')
axes[1].set_ylabel('Cohen Kappa Score')
axes[1].set_title('Cohen Kappa Comparison', fontweight='bold')
axes[1].grid(axis='y', alpha=0.3)
for i, v in enumerate(comparison_df['Cohen Kappa']):
    axes[1].text(i, v + 0.01, f"{v:.4f}", ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('/content/model_comparison.png', dpi=150)
plt.show()

best_model_idx = comparison_df['Test Acc'].idxmax()
best_model = comparison_df.iloc[best_model_idx]
print(f"\nBest performing model: {best_model['Model']}")
print(f"Test Accuracy: {best_model['Test Acc']:.2f}%")
print(f"Cohen Kappa: {best_model['Cohen Kappa']:.4f}")

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

models_data = [
    ('CustomCNN', train_hist_custom, val_hist_custom),
    ('ResNet18', train_hist_resnet, val_hist_resnet),
    ('EfficientNet-B0', train_hist_effnet, val_hist_effnet),
    ('MobileNetV2', train_hist_mobile, val_hist_mobile)
]

for idx, (name, train_hist, val_hist) in enumerate(models_data):
    row = idx // 2
    col = idx % 2

    ax = axes[row, col]
    epochs_range = range(1, len(train_hist['loss']) + 1)

    ax2 = ax.twinx()

    line1 = ax.plot(epochs_range, train_hist['loss'], 'b-', label='Train Loss', linewidth=2)
    line2 = ax.plot(epochs_range, val_hist['loss'], 'r-', label='Val Loss', linewidth=2)
    line3 = ax2.plot(epochs_range, train_hist['acc'], 'b--', label='Train Acc', linewidth=2)
    line4 = ax2.plot(epochs_range, val_hist['acc'], 'r--', label='Val Acc', linewidth=2)

    ax.set_xlabel('Epoch', fontsize=11)
    ax.set_ylabel('Loss', fontsize=11, color='black')
    ax2.set_ylabel('Accuracy (%)', fontsize=11, color='black')
    ax.set_title(f'{name} - Training Progress', fontsize=12, fontweight='bold')
    ax.grid(True, alpha=0.3)

    lines = line1 + line2 + line3 + line4
    labels = [l.get_label() for l in lines]
    ax.legend(lines, labels, loc='center right')

plt.tight_layout()
plt.savefig('/content/training_curves.png', dpi=150)
plt.show()

print("Training curves saved")